# Example values
components:
  requestBodies:
    
    NewProduct:
      type: object
      required:
        - idProduct
        - title
        - description
        - code
        - price
        - status
        - stock
        - category
      properties:
        idProduct:
          type: string
          description: Identificador unico para cada producto ingresado al sistema.
        title:
          type: string
          description: Titulo o nombre del producto.
        description:
          type: string
          description: Ofrece mayor detalle del producto.
        code:
          type: string
          description: Identificador de menor longitud y mayor elocuencia del producto.
        price:
          type: number
          description: Numero que indica el precio del producto.
        status:
          type: boolean
          description: Indicador que muestra el estado del producto.
        stock:
          type: number
          description: Numero de unidades disponibles.
        category:
          type: string
          description: Grupo al cual pertenece dicho producto.
        thumbnails:
          type: array
          description: Coleccion de imagenes del producto.
        owner:
          type: string
          description: Usuario que añadio el producto al sistema.
      example:
         idProduct: 4ughd73658fn
         title: desktop computer
         description: 32GB RAM, 1TB SSD, Monitor 60Hz
         code: dc56
         price: 123.78
         status: true
         stock: 3
         category: technology
         thumbnails: [http://photo1.url.png,http://photo2.url.png,http://photo3.url.png]
         owner: Elon Musk
    
    NewUser:
      type: object
      required:
        - idUser
        - first_name
        - last_name
        - email
        - age
        - password
        - rol
        - cartId
      properties:
        idUser:
          type: string
          description: Identificador unico para cada usuario ingresado al sistema.
        first_name:
          type: string
          description: Nombre real del usuario.
        last_name:
          type: string
          description: Apellido del usuario.
        email:
          type: string
          description: Direccion de correo electronico del usuario.
        age:
          type: number
          description: Edad del usuario.
        password:
          type: string
          description: constraseña del usuario.
        rol:
          type: string
          description: titulo que define los privilegios en el sistema.
        cartId:
          type: string
          description: Identificador del carrito de compra asignado.
      example:
         idUser: 4ughd73658fn
         first_name: Juan Manuel
         last_name: Enriquez Vega
         email: juanMa26@correo.com
         age: 27
         password: as3(23&^c6ds8r&*
         rol: usuario premium 
         cartId: 6ushd7c658fc

    NewChat:
      type: object
      required:
        - idChat
        - user
        - message
      properties:
        idChat:
          type: string
          description: Identificador unico para el chat asignado a cada usuario.
        user:
          type: string
          description: Id del emisor.
        message:
          type: string
          description: Mensaje enviado en la plataforma.
      example:
         idChat: 4ughd73658fn
         user: 456e4s5adad
         message: hola mucho gusto.

    NewCart:
      type: object
      required:
        - idCart
      properties:
        idCart:
          type: string
          description: Identificador unico para el carrito asignado a cada usuario.
        products:
          type: array
          description: Conjunto de productos añadidos por el usuario.
      example:
         idCart: 4ughd73658fn
         products: [
          {
            product: "acds546",
            quantity: 6
          },
          {
            product: "edds060",
            quantity: 2
          }
         ]
    
    NewTicket:
      type: object
      required:
        - idTicket
        - code
        - purchase_datetime
        - amount
        - purchaser
      properties:
        idTicket:
          type: string
          description: Identificador unico para el ticket de compra.
        code:
          type: string
          description: Identificador mas corto y elocuentel ticket de compra.
        purchase_datetime:
          type: date
          description: Fecha y hora en la que se realizo la compra.
        amount:
          type: number
          description: Cantidad total a pagar de la compra.
        purchaser:
          type: string
          description: Informacion del cliente.
      example:
         idTicket: 4ughd73658fn
         code: cpjs5
         purchase_datetime: 10/11/23, 11:57
         amount: 753
         purchaser: 'Manolo Diaz'